Update index.md
carpentries/instructor-training pull request #1358
Opened 2022-04-22 13:56 UTC by tefer0

On line 17, and Unix shell between R and python programming, as part of what is not taught in programming.
#checkout_process

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
instructor.training@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

2022-04-22 14:13 UTC, brownsarahm requested changes
The Unix shell is not a programming language, but it could be included in this sentence in a different place.

2022-04-22 14:13 UTC, brownsarahm commented on index.md
> +* How to program in R, Unix shell or Python, use Git or SQL, or any of the other topics taught in Data Carpentry, Library Carpentry, or Software Carpentry workshops.
```suggestion
* How to program in R or Python, use the Unix shell, Git or SQL, or any of the other topics taught in Data Carpentry, Library Carpentry, or Software Carpentry workshops.
```

2022-04-22 14:13 UTC, tefer0 commented on index.md
> +* How to program in R, Unix shell or Python, use Git or SQL, or any of the other topics taught in Data Carpentry, Library Carpentry, or Software Carpentry workshops.
Thank you for the correction

2022-04-22 14:25 UTC, tefer0 reviewed
Thank you for the correction.

2022-04-26 14:51 UTC, brownsarahm approved these changes

2022-04-26 14:51 UTC, merged