Checkout updates 2023
carpentries/instructor-training pull request #1548
Opened 2023-05-31 20:31 UTC by karenword

Proposed updates to address changes to the Instructor checkout process. Not to be merged until rollout.

2023-06-14 23:00 UTC, Talishask requested changes
Shared some updates to provide a full overview of checkout at the top, with folks only needing to go into the bottom sections if they are looking for specific details.

2023-07-15 00:06 UTC, karenword commented on learners/checkout.md
> +2. [Complete a Teaching Demonstration](#demonstration). A 1-hour session where trainees demonstrate 5 minutes of teaching and receive and share feedback with their peers.
```suggestion
2. [Complete a Teaching Demonstration](#demonstration). A 1-hour session where trainees demonstrate 5 minutes of participatory instruction and share feedback, with evaluation by a Carpentries Instructor Trainer.
```

2023-07-15 20:51 UTC, karenword commented on learners/checkout.md
> +Welcome Sessions and Teaching Demonstrations will be tracked automatically based on data shared by session hosts. **For the “Get Involved” step, trainees must login to AMY to report which participati
```suggestion
 **For the “Get Involved” step, trainees must login to AMY to report which participation option they would like to have counted.**  Welcome Sessions and Teaching Demonstrations will be tracked automatically based on data shared by session hosts.
```

2023-07-26 17:22 UTC, klbarnes20 approved these changes
Made two small changes, but otherwise it looks great!

2023-07-26 17:22 UTC, klbarnes20 commented on learners/checkout.md
> +I have you have a question, you can email us at instructor.training@carpentries.org or visit the [#checkout-support](https://swc-slack-invite.herokuapp.com/) slack channel.
```suggestion
If you have a question, you can email us at instructor.training@carpentries.org or visit the [#checkout-support](https://swc-slack-invite.herokuapp.com/) slack channel.
```

2023-07-26 17:22 UTC, klbarnes20 commented on learners/checkout.md
> +(An example of a lesson: [R for Reproducible Scientific Analysis][r-gapminder]). The episodes within a lesson are numbered and listed in a collapsible window on the left side of the main lesson page.
```suggestion
(An example of a lesson: [R for Reproducible Scientific Analysis][r-gapminder]). The episodes within a lesson are numbered and listed in a collapsible window on the left side of the main lesson page. After 14 August, 2023, **you do NOT need to prepare a full lesson**, but should select a single episode within that lesson. 
```

2023-08-03 21:46 UTC, karenword commented on learners/checkout.md
> +### Attend an Instructor Meeting, Regional Call, or Other Community Programming
```suggestion
### Attend a Regional Call, Skill-Up Session, or Other Community Programming
```

2023-08-03 21:47 UTC, karenword commented on learners/checkout.md
> +- Attend an Instructor Meeting, regional call, or other community programming
```suggestion
- Attend a regional call, skill-up session, or other community programming
```

2023-08-05 00:16 UTC, karenword commented on learners/checkout.md
> +contribution process is a great way to complete your Instructor certification.
```suggestion
contribution process is a great way to complete your Instructor certification.  
If you would like help making a lesson contribution consider making a post in the #first-time-contributors channel on [The Carpentries Slack][slack]. This channel is overseen by our Curriculum team and can be useful for contribution questions long after you have completed your checkout process. 
```

2023-08-05 00:16 UTC, karenword commented on learners/checkout.md
>  [start-points]: https://carpentries.github.io/instructor-training/demo_lessons
```suggestion
[start-points]: https://carpentries.github.io/instructor-training/demo_lessons
[slack]: https://swc-slack-invite.herokuapp.com/
```

2023-08-05 00:22 UTC, karenword commented
Conflicts resolved and ready for merge on 13 August. Please check for conflicts and resolve promptly if any additional changes are made in the interim.

2023-08-13 23:56 UTC, merged