Fix link format in demo lessons
carpentries/instructor-training pull request #1622
Opened 2023-11-17 14:31 UTC by ndporter

Closes #1598.

Replace all episode links containing trailing `/` with full link (`.html`) or remove `/` for compatibility with workbench.

More information:
Previously, links to episodes could end in one of 3 ways and resolve correctly. For example any of the following should have worked:

- `https://swcarpentry.github.io/git-novice-es/02-setup.html`
- `https://swcarpentry.github.io/git-novice-es/02-setup/`
- `https://swcarpentry.github.io/git-novice-es/02-setup`

With the upgrade to workbench, the second (trailing `/`) no longer resolves.

2023-11-17 14:32 UTC, ndporter commented
@carpentries/instructor-training-maintainers Can someone please check that all links resolve correctly before merging? Thanks!

2023-11-17 21:29 UTC, karenword commented on learners/demo_lessons.md
> +| [Data Wrangling and Processing](https://datacarpentry.org/wrangling-genomics.html) |  \* [Assessing Read Quality](https://datacarpentry.org/wrangling-genomics/02-quality-control.html) <br/> \* [Tri
```suggestion
| [Data Wrangling and Processing](https://datacarpentry.org/wrangling-genomics/) |  \* [Assessing Read Quality](https://datacarpentry.org/wrangling-genomics/02-quality-control.html) <br/> \* [Trimming and Filtering](https://datacarpentry.org/wrangling-genomics/03-trimming.html) <br/> \* [Automating a Variant Calling Workflow](https://datacarpentry.org/wrangling-genomics/05-automation.html)  | none |  The other episodes depend on actions taken earlier in the lesson - consult [_Teaching Episodes with Dependencies_](#dependencies). <br/>If using [Assessing Read Quality](https://datacarpentry.org/wrangling-genomics/02-quality-control.html), begin with `gunzip SRR2584863_1.fastq.gz`  |
```

2023-11-17 21:29 UTC, karenword commented on learners/demo_lessons.md
> +| [Programming with Python](https://swcarpentry.github.io/python-novice-inflammation/) | any other episode  | [Debugging](https://swcarpentry.github.io/python-novice-inflammation/09-debugging) |  |
```suggestion
| [Programming with Python](https://swcarpentry.github.io/python-novice-inflammation/) | any other episode  | [Debugging](https://swcarpentry.github.io/python-novice-inflammation/11-debugging.html) |  |
```

2023-11-17 21:31 UTC, karenword commented
(apparently *setup* pages do still resolve with the training / and don't resolve with .html)

2023-11-20 17:39 UTC, dpshelio requested changes
Suggesting some changes to keep consistency. I'll vote for all to include the `.html` which is the pattern you've used the most in your update. For style lessons, I'd recommend either ending on `/` or including the `/index.html`.

2023-11-20 17:39 UTC, dpshelio commented on learners/demo_lessons.md
> +| [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/) | any other episode  | \* [Writing Good Software](https://swcarpentry.github.io/r-novice-gapminder/16-wra
```suggestion
| [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/) | any other episode  | \* [Writing Good Software](https://swcarpentry.github.io/r-novice-gapminder/16-wrap-up.html)  |  |
```

2023-11-20 17:39 UTC, dpshelio commented on learners/demo_lessons.md
> +| [Using Databases and SQL](https://swcarpentry.github.io/sql-novice-survey/) | any other episode  | [Data Hygiene](https://swcarpentry.github.io/sql-novice-survey/08-hygiene) |  |
```suggestion
| [Using Databases and SQL](https://swcarpentry.github.io/sql-novice-survey/) | any other episode  | [Data Hygiene](https://swcarpentry.github.io/sql-novice-survey/08-hygiene.html) |  |
```

2023-11-20 17:39 UTC, dpshelio commented on learners/demo_lessons.md
> +| [Automation and Make](https://swcarpentry.github.io/make-novice) |  \* [Introduction](https://swcarpentry.github.io/make-novice/01-intro)<br/> \*  [Makefiles](https://swcarpentry.github.io/make-nov
```suggestion
| [Automation and Make](https://swcarpentry.github.io/make-novice) |  \* [Introduction](https://swcarpentry.github.io/make-novice/01-intro.html)<br/> \*  [Makefiles](https://swcarpentry.github.io/make-novice/02-makefiles.html) | \* [Conclusion](https://swcarpentry.github.io/make-novice/09-conclusion.html) | Later episodes depend on actions taken earlier in the lesson - consult [_Teaching Episodes with Dependencies_](#dependencies). |
```

2023-11-20 17:39 UTC, dpshelio commented on learners/demo_lessons.md
> +| [Version Control with Mercurial](https://swcarpentry.github.io/hg-novice/) |  \* [Configuring Mercurial](https://swcarpentry.github.io/hg-novice/02-configuration)<br/> \* [Creating a Repository](ht
Ideally... I'd use the trailing `/`, at it's happening behind the scenes. It goes to a `index.html` page. Or to keep consistency with all, to use `/index.html`.

2023-11-20 17:44 UTC, ndporter commented
@zkamvar Which formats are most robust over time? We should just choose those right now and stick with it (and maybe share with the maintainer community in general).

- For setup/lesson main page: `https://domain/dir/` | `https://domain/dir/index.html'
- For episodes: `https://domain/dir/episode` | `https://domain/dir/episode.html`

2023-11-20 17:54 UTC, zkamvar commented
> @zkamvar Which formats are most robust over time? We should just choose those right now and stick with it (and maybe share with the maintainer community in general).
> 
> * For setup/lesson main page: `https://domain/dir/` | `https://domain/dir/index.html'
> * For episodes: `https://domain/dir/episode` | `https://domain/dir/episode.html`

I would go with the more explicit form of `dir/episode.html` and `dir/index.html`

2023-11-20 18:51 UTC, ndporter commented
@tobyhodges [Mercurial](https://swcarpentry.github.io/hg-novice/index.html) is still in here but I see it's not workbench, isn't listed on SWC lessons, and is stale from 2018. Can you confirm whether it should be in the demos list?

2023-11-20 19:01 UTC, ndporter commented
All links tested and updated, along with some outdated titles. Awaiting response on whether to include Mercurial. Otherwise, should be ready unless someone else wants to check again.

2023-11-20 19:01 UTC, ndporter reviewed
Trying to resolve review requests from @dpshelio but having issues. Hopefully this clears the hold.

2023-11-20 19:19 UTC, merged