Replace cdh with Collaborative Lesson Development Training
carpentries/instructor-training pull request #1685
Opened 2024-06-27 18:21 UTC by ndporter

Replace link to the retired curriculum development handbook (which states): `The Carpentries is preparing to retire this handbook at the end of 2023. Existing content that has not already been replicated elsewhere will be relocated. See the relevant issue on the source repository for more details.`

Add link to current training.

2024-06-27 18:23 UTC, ndporter commented
@ErinBecker or @tobyhodges please verify this is the correct link and approach. Thanks!

2024-07-15 16:50 UTC, tobyhodges requested changes
Thanks @ndporter! I have suggested a change to the wording of the link.

2024-07-15 16:50 UTC, tobyhodges commented on episodes/15-carpentries.md
>  Another resource, [The Carpentries Curriculum Development Handbook][cdh], provides a guide to
```suggestion
Another resource, [the Collaborative Lesson Development Training curriculum][cld], provides a guide to
```

2024-07-15 17:07 UTC, ndporter commented
I tried to approve your changes (and did merge them in) @tobyhodges but it's still showing as "changes requested". Once that resolves either on its own or with coaxing, we should probably have someone else from @carpentries/instructor-training-maintainers check it and merge.

2024-07-16 12:23 UTC, tobyhodges approved these changes

2024-07-16 16:02 UTC, brownsarahm commented
🎉

2024-07-16 16:02 UTC, merged