fixing links
carpentries/instructor-training pull request #1768
Opened 2024-12-14 15:16 UTC by brownsarahm

I tried to resolve the conflicts on #1490 in a codespace, only to realized after I had gone through all of the conflicts that I could not push to the branch for the pr. I pushed to my own branch and I think the only choice I can do is make a new PR directly 

(we could technically make a PR to @dpshelio 's branch, have him merge that and then merge #1490 but he said he is limited capacity, so I want to give us a path forward without him in the loop)

2024-12-17 18:07 UTC, ndporter requested changes
In addition to inline suggestions, (template-md) and rmd version should be [template-md/rmd] to reference named link (round parentheses reference hard links). Git didn't like me putting suggestions on them.

More generally, should we use a consistent style, either:

1. ...see [link][link] OR
2. ...see name-of-thing at [link][link] OR
3. ...see [name-of-thing][link]

I don't recall exactly where the discussion came down. Currently, these revisions are mostly a mix of 1 and 2. My understanding is 3 is best for accessibility because the surface text describes the link, but it can be an issue for copying and pasting exercises into etherpads. Either way, we should try to do them all the same.

2024-12-17 18:55 UTC, ndporter commented on episodes/09-eia.md
> +1. Take a moment to read through the [https://carpentries.org/values/][core-values]
We can use the section id to go right there, at least: https://carpentries.org/about-us/#our-values.

2024-12-17 18:56 UTC, ndporter commented
> 
> More generally, should we use a consistent style, either:
> 
> 1. ...see [link][link] OR
> 2. ...see name-of-thing at [link][link] OR
> 3. ...see [name-of-thing][link]
> 
> I don't recall exactly where the discussion came down. Currently, these revisions are mostly a mix of 1 and 2. My understanding is 3 is best for accessibility because the surface text describes the link, but it can be an issue for copying and pasting exercises into etherpads. Either way, we should try to do them all the same.

@carpentries/core-team-curriculum what is the current guidance on link practice, given the constraints above about both accessibility and copy-paste readiness for pads?

2024-12-18 17:48 UTC, tobyhodges commented
> @carpentries/core-team-curriculum what is the current guidance on link practice, given the constraints above about both accessibility and copy-paste readiness for pads?

Indeed, accessibility best practice would be descriptive link text. But as this will not play nicely with the etherpad generation, I suggest either option 2 (_see name-of-thing at [link][link]_) or a redundant approach that makes the etherpad look nicer: _see [name-of-thing][link] ([link][link])_.

I marginally prefer the latter, while conceding that the redundancy will still be annoying for screen reader users. I leave the final decision up to the Maintainers.

2024-12-18 18:37 UTC, brownsarahm commented
I think the latter approach has the additional advantage of being easy to switch to the only best practice option, if the template and/or etherpad tech changes

2025-01-10 15:10 UTC, brownsarahm commented
I don't understand: 
> In addition to inline suggestions, (template-md) and rmd version should be [template-md/rmd] to reference named link (round parentheses reference hard links). Git didn't like me putting suggestions on them.

can you give the file(s) and line(s) of at least one occurence to help me parse what you are referring to (I only resolved the merge conflicts on this PR it is not really mostly my work)

2025-01-14 16:40 UTC, brownsarahm commented on instructors/checkout.md
> +- any [Data Carpentry]({{ site.dc_site }}/lessons/), [Library Carpentry]({{ site.lc_site }}/lessons/), or [Software Carpentry]({{ site.swc_site }}/lessons/) lesson
good catch I removed the file now

2025-01-14 16:42 UTC, tobyhodges approved these changes
Thanks @brownsarahm 🙌

2025-01-14 16:49 UTC, ndporter approved these changes
Looks good to me.

2025-01-14 16:51 UTC, ndporter commented
Note on this: there are some places with mid-line links where this technique starts to look pretty messy like:

> Discuss what you have read in small groups. As questions arise, you may wish to refer to our complete Code of Conduct section in The Carpentries Handbook: https://docs.carpentries.org/policies/coc/ or to the Transparency Reports released by The Carpentries Code of Conduct Committee: https://github.com/carpentries/executive-council-info/tree/master/code-of-conduct-transparency-reports

I don't think this PR includes any of those, but we should probably set these up so there are line breaks after any link that's spelled out like this.

2025-01-14 16:58 UTC, brownsarahm commented
Do you want to make those changes here or open a new issue for them?

2025-01-14 17:07 UTC, ndporter commented
> Do you want to make those changes here or open a new issue for them?

I suppose I should open a new issue. Maybe I'll try later today to go through the whole AIO and look for any of those.

2025-01-14 17:10 UTC, merged